<?php

// Template to display store availability on product view.

use Magento\Framework\Escaper;
use Smile\RetailerOffer\Block\Catalog\Product\Retailer\Availability;

/** @var Availability $block */
/** @var Escaper $escaper */
?>
<div id="catalog-product-retailer-availability"
     data-block="catalog-product-retailer-availability"
     class="block catalog-product-retailer-availability"
>
    <div class="block catalog-product-stores-availability-content"
         data-role="dropdownDialog"
         data-bind="scope: 'catalog-product-retailer-availability'"
         data-mage-init='{
           "Magento_Ui/js/modal/modal":{
             "trigger":".showavailability",
             "buttons":[],
             "modal":true
           }
         }'>
        <div class="fulltext-search-wrapper">
            <div class="geocoder-wrapper">
                <div class="block-title">
                    <strong role="heading" aria-level="1" data-bind="text: searchTitleText"></strong>
                </div>

                <form class="form" data-bind="submit: onSearchOffers">
                    <div class="field">
                        <input type="text" name="text"
                               data-bind="value: fulltextSearch, attr: {placeholder: searchPlaceholderText}"/>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="action primary">
                                <span data-bind="text: searchButtonText"></span>
                            </button>
                        </div>
                        <div data-bind="{ scope: requestChild('geocoder')}">
                            <div data-bind="afterRender: initGeocoder">
                                <button data-bind="click: $parent.geolocalizeMe.bind($parent)" class="action primary">
                                    <span data-bind="text: $parent.geolocationButtonText"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="store-offers-list" data-role="content">
            <ul data-bind="foreach: displayedOffers()">
                <li data-bind="template: $parent.storeOffersListTemplate" class="result-item"></li>
            </ul>
        </div>

        <div data-bind="{ scope: requestChild('map')}">
            <div id="store-view-map" class="store-view-map clearfix">
                <div id="map-popin-availability" class="map" data-bind="afterRender: initMap"></div>
            </div>
        </div>
    </div>
    <div class="catalog-product-retailer-availability-content">
        <div class="title">
            <span><?= $escaper->escapeHtml(__('Store availability : ')) ?></span>
        </div>
        <div class="content-wrapper" data-bind="scope: 'catalog-product-retailer-availability'">
            <div data-bind="visible: hasStore()" class="current-store">
                <p class="availability"
                   data-bind="css: { inStock: getIsInStock() == true, outOfStock: getIsInStock() == false }">
                    <span data-bind="text: getStoreName() + ':' " class="store-name-value"></span>
                    <span data-bind="html: getStockLabel()" class="stock-label"></span>
                </p>
            </div>
        </div>
    </div>
    <div class="action showavailability" data-bind="scope: 'catalog-product-retailer-availability'">
        <a href="#" class="text" data-bind="text: getLinkLabel(), click: loadRetailerAvailabilityModal"></a>
    </div>
</div>

<script type="text/x-magento-init">
    { "*" : { "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?> } }
</script>
