<?php

// Summary panel for offer edition (product)

use Magento\Framework\Escaper;
use Smile\RetailerOffer\Block\Adminhtml\RetailerOffer\Summary\Product;

/** @var Product $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getProduct()): ?>
    <div class="retailer-offer-summary-product">
        <h3><span><?= $escaper->escapeHtml(__('Product :')) ?></span></h3>

        <div class="product-image">
            <img src="<?= $escaper->escapeHtmlAttr($block->getProductImage()) ?>" />
        </div>

        <div class="info">
            <h3>
                <span class="product-name"><?= $escaper->escapeHtml($block->getProduct()->getName()) ?></span>
            </h3>
            <p class="sku"><?= $escaper->escapeHtml(__('SKU : %1', $block->getProduct()->getSku())) ?></p>
            <?php if ($block->getProduct()->getSpecialPrice()): ?>
                <p class="price regular-price"><del><?= /* @noEscape */ $block->getProductPrice() ?></del></p>
                <p class="price special-price"><?= /* @noEscape */ $block->getProductSpecialPrice() ?></p>
            <?php else: ?>
                <p class="price"><?= /* @noEscape */ $block->getProductPrice() ?></p>
            <?php endif ?>
            <p class="stock"><?= $escaper->escapeHtml(__('Availability : %1', $block->getProductStockLabel())) ?></p>
            <p class="status"><?= $escaper->escapeHtml(__('Status : %1', $block->getProductStatusLabel())) ?></p>
        </div>
    </div>
<?php endif ?>
