<?php

// Summary panel for offer edition (retailer)

use Magento\Framework\Escaper;
use Smile\RetailerOffer\Block\Adminhtml\RetailerOffer\Summary\Retailer;

/** @var Retailer $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRetailer()): ?>
    <div class="retailer-offer-summary-retailer">
        <h3><span><?= $escaper->escapeHtml(__('Retailer :')) ?></span></h3>
        <div class="info">
            <h3>
                <span class="retailer-name"><?= $escaper->escapeHtml($block->getRetailer()->getName()) ?></span>
            </h3>
            <p class="sku"><?= $escaper->escapeHtml(__('Code : %1', $block->getRetailer()->getSellerCode())) ?></p>
            <p class="status"><?= $escaper->escapeHtml(__('Status : %1', $block->getRetailerStatusLabel())) ?></p>
        </div>
    </div>
<?php endif ?>
