<?php

// Summary panel for offer edition

use Magento\Framework\Escaper;
use Smile\RetailerOffer\Block\Adminhtml\RetailerOffer\Summary;

/** @var Summary $block */
/** @var Escaper $escaper */
?>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="title"><span><?= $escaper->escapeHtml(__('Offer Summary')) ?></span></strong>
    </div>
    <div class="admin__fieldset-wrapper-content">
        <div class="admin__fieldset">
            <div class="retailer-offer-summary">
                <?= $block->getProductSummaryBlock()->toHtml() ?>
                <?= $block->getRetailerSummaryBlock()->toHtml() ?>
                <div class="clear abs-clearer"></div>
            </div>
        </div>
    </div>
</div>
